# Generated by Django 5.2.5 on 2026-05-15 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_sub', models.CharField(blank=True, max_length=255, null=True)),
                ('user_tenant_slug', models.CharField(blank=True, max_length=50, null=True)),
                ('requested_tenant_slug', models.CharField(blank=True, max_length=50, null=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('outcome', models.CharField(choices=[('allowed', 'Allowed'), ('unauthorized_tenant', 'Unauthorized Tenant Access'), ('invalid_token', 'Invalid Token'), ('missing_token', 'Missing Token')], max_length=30)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('handled_by_instance', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_logs_timesta_e93820_idx'), models.Index(fields=['user_sub', '-timestamp'], name='audit_logs_user_su_1cae95_idx'), models.Index(fields=['outcome', '-timestamp'], name='audit_logs_outcome_202983_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('period', models.CharField(help_text="Período del reporte, ej: '2026-Q1', '2026-05'", max_length=20)),
                ('total_cost_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payload', models.JSONField(default=dict, help_text='Detalle del reporte (breakdown por servicio, región, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reportes.tenant')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='reports_tenant__b9fd76_idx')],
            },
        ),
    ]
